# Generated by Django 6.0.3 on 2026-04-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('pH', 'pH'), ('C', 'Temperature (C)'), ('mg/L', 'Concentration (mg/L)'), ('%', 'Percentage (%)')], max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
